-- ============================================================
-- 058: Life At Lakewood neighborhoods, terms and tag icons
--
-- Generated by scripts/listings-lakewood-villages.mjs, which is the file to
-- read for why each term is what it is. The short version:
--
-- The source is the site's dashboard page code -- the
-- `subDivisionName.search(...)` chain that assigns Village / VillageURL /
-- village1, and the three tag ternaries in setDataObject. Names, page URLs,
-- Wix item ids, villageSortHelp values and all three tag icons are
-- transcribed from it and then confirmed against an export of the live
-- HousesforSale collection (404 rows, 2026-09-17): every neighborhood
-- carries exactly one blue/purple/green icon across its listings, and each
-- is the constant the ternary names.
--
-- THE TERMS ARE DELIBERATELY NOT A TRANSCRIPTION. The old pipeline pulled a
-- curated MLS_id_list and used its terms only to sort already-chosen
-- listings into neighborhoods; the engine has no such list, so the same term
-- becomes the filter deciding whether a listing belongs to the site at all.
-- Migration 056 is what that difference costs when it is missed.
--
-- Nine of the dashboard's terms already match subdivisions the engine holds
-- in five cities this site does not even cover:
--
--   isles       21 subdivisions  ALAMEDA ISLES, ENGLEWOOD ISLES, LEMON BAY ISLES
--   del webb     5               DEL WEBB AT BAYVIEW, DEL WEBB SUNCHASE (Parrish)
--   emerald      2               EMERALD HARBOR, EMERALD POINTE SOUTH
--   edgewater    1               EDGEWATER CENTER
--   esplanade    1               ESPLANADE AT WELLEN PARK
--   lake club    1               PINEBROOK LAKE CLUB
--   riverwalk    1               RIVERWALK MHP CO-OP
--   sweetwater   1               SWEETWATER VILLAS AT SOUTHWOOD
--   windward     1               WINDWARD BAY AMD
--
-- So each term was narrowed to the longest form the export proves every MLS
-- spelling of that neighborhood carries -- "isles at lakewood ranch" rather
-- than "isles", "harmony at lakewood" rather than "harmony", "edgewater
-- village" + "moorings at edgewater" rather than "edgewater". The
-- dashboard's "country club village" is dropped outright: every row it would
-- have caught is already caught by one of the other two Country Club terms.
--
-- VERIFIED against the export after the change: 403 of the 404 rows file
-- under exactly the neighborhood the site files them under, and none files
-- under a different one. The single exception is one listing whose
-- subdivision is the bare word ESPLANADE, which no anchored term can reach;
-- it lands in the unmatched view rather than being bought with a term that
-- would also take Sarasota's Esplanades. __tests__/unit/listings/
-- lakewood-villages.test.ts holds that check.
--
-- SIX TERMS ARE STILL BARE, because the MLS writes those names with nothing
-- to anchor to: aurora, cresswind, del webb, indigo, lake club, palisades.
-- They are the open risk this site carries into its first shadow run, and
-- scripts/listings-lakewood-probe.ts is what checks them against the real
-- Lakewood Ranch / Bradenton / Sarasota inventory before switch-on.
--
-- ONE THING CHANGES ON THE SITE. The dashboard has two blocks for
-- Summerfield and Riverwalk but writes the same village1 and the same page
-- for both ("summerfield-and-riverwalk"): one Villages row, two labels.
-- ls_villages has a unique index on (site_id, wix_item_id) because
-- village-stats.ts writes each neighborhood's active count and ranges back
-- to its row, and two neighborhoods pointing at one row would overwrite each
-- other. So they are one neighborhood here, named Summerfield, carrying both
-- pairs of terms. The two RIVERWALK listings will read "Summerfield", and
-- the site's filter loses Riverwalk as an option. Everything else is
-- unchanged. Put to Jeff on 2026-09-18 and confirmed; a real Riverwalk row
-- in the neighborhoods collection undoes it in one migration if he changes
-- his mind.
--
-- Applied to production via the Supabase MCP on 2026-09-17 as migration
-- listings_lakewood_villages.
-- ============================================================

-- 39 neighborhoods, 61 subdivision terms (scripts/listings-lakewood-villages.mjs).
WITH site AS (SELECT id FROM ls_sites WHERE domain = 'lifeatlakewood.com'),
icon(key, url) AS (VALUES
    ('villageSpa', 'https://static.wixstatic.com/media/d0be81_b31fc860894445a89f08c3fb8b530e34~mv2.png/v1/fit/w_924,h_520/d0be81_b31fc860894445a89f08c3fb8b530e34~mv2.png'),
    ('maintenance', 'https://static.wixstatic.com/media/d0be81_4f9303a511cc42fa986017d290513167~mv2.png'),
    ('clubhouse', 'https://static.wixstatic.com/media/d0be81_aae6b9125c784fffbe6b679d403c01d6~mv2.png/v1/fit/w_924,h_520/d0be81_aae6b9125c784fffbe6b679d403c01d6~mv2.png'),
    ('gated', 'https://static.wixstatic.com/media/d0be81_1f03e4c773b540359c5228a34fcf0ff3~mv2.png/v1/fit/w_924,h_520/d0be81_1f03e4c773b540359c5228a34fcf0ff3~mv2.png'),
    ('dogPark', 'https://static.wixstatic.com/media/d0be81_2ce27035a8414b3985909fd0b3060f29~mv2.png/v1/fit/w_924,h_520/d0be81_2ce27035a8414b3985909fd0b3060f29~mv2.png'),
    ('scenicWalks', 'https://static.wixstatic.com/media/d0be81_62b3be4d3f8b4d09ab6f1e14225c7349~mv2.png/v1/fit/w_924,h_520/d0be81_62b3be4d3f8b4d09ab6f1e14225c7349~mv2.png'),
    ('kidsTotlot', 'https://static.wixstatic.com/media/d0be81_da59bb5bd8b841f28d2166013b0a68d1~mv2.png/v1/fit/w_924,h_520/d0be81_da59bb5bd8b841f28d2166013b0a68d1~mv2.png'),
    ('totLot', 'https://static.wixstatic.com/media/d0be81_1404b3ad1f824281a42918207217e9a9~mv2.png/v1/fit/w_924,h_520/d0be81_1404b3ad1f824281a42918207217e9a9~mv2.png'),
    ('tennis', 'https://static.wixstatic.com/media/d0be81_0342a27fc9e14170b51b20affba893aa~mv2.png/v1/fit/w_924,h_520/d0be81_0342a27fc9e14170b51b20affba893aa~mv2.png'),
    ('greenTennis', 'https://static.wixstatic.com/media/d0be81_34fcb186a4a54099911cf64a9ec80359~mv2.png/v1/fit/w_924,h_520/d0be81_34fcb186a4a54099911cf64a9ec80359~mv2.png'),
    ('greenGolf2', 'https://static.wixstatic.com/media/d0be81_ba68daa783d14ab68ac7dc7082fa3d63~mv2.png'),
    ('villagePool', 'https://static.wixstatic.com/media/d0be81_51600c69200340bf92f94d78f4f47d60~mv2.png'),
    ('scenicViews', 'https://static.wixstatic.com/media/d0be81_a065767388d54189879749c19953381f~mv2.png'),
    ('greenPickleball', 'https://static.wixstatic.com/media/d0be81_2212bb342e44447a9ecc8ca4951b6a01~mv2.png/v1/fit/w_924,h_520/d0be81_2212bb342e44447a9ecc8ca4951b6a01~mv2.png')
),
village_rows(name, wix_slug, wix_item_id, page_url, sort_help, blue, purple, green) AS (VALUES
    ('Arbor Grande', 'arbor-grande', '107fa313-ad7f-42c1-90c9-7c964dd37c7e', 'https://www.lifeatlakewood.com/arbor-grande', 'Arbor Grande', 'villageSpa', 'gated', 'dogPark'),
    ('Aurora', 'aurora', 'cad6ac3f-5e35-4078-a4cd-9afe1d6ea60e', 'https://www.lifeatlakewood.com/aurora', 'Aurora', 'maintenance', 'totLot', 'villagePool'),
    ('Avalon Woods', 'avalon-woods', '216a3208-8f23-4eaa-9af0-726792f205c9', 'https://www.lifeatlakewood.com/avalon-woods', 'Avalon Woods', 'kidsTotlot', NULL, NULL),
    ('Azario - Esplanade', 'azario-esplanade', '8e57d32f-c8ec-44d1-9027-04a6dddee749', 'https://www.lifeatlakewood.com/azario-esplanade', 'Esplanade - Azario', 'villageSpa', 'tennis', 'greenGolf2'),
    ('Azario - Park East', 'azario-park-east', '935d19a3-2a46-464f-8553-71a220c4c4b7', 'https://www.lifeatlakewood.com/azario-park-east', 'Park East - Azario', 'clubhouse', 'totLot', 'villagePool'),
    ('Bridgewater', 'bridgewater', '959e7850-a310-401b-b137-cad7e57bcdfa', 'https://www.lifeatlakewood.com/bridgewater', 'Bridgewater', 'scenicWalks', 'gated', 'scenicViews'),
    ('Central Park', 'central-park', '042aeeb9-6363-40e6-8b65-3c2a1bb7c0b2', 'https://www.lifeatlakewood.com/central-park', 'Central Park', 'villageSpa', 'gated', 'greenTennis'),
    ('Country Club East', 'country-club-east', 'c5b82142-2550-40f5-9ce2-74b701619455', 'https://www.lifeatlakewood.com/country-club-east', 'Country Club East', 'clubhouse', 'gated', 'greenGolf2'),
    ('Cresswind', 'cresswind', 'b64fa510-088f-4799-ba71-a26e5e1a8d6d', 'https://www.lifeatlakewood.com/cresswind', 'Cresswind', 'clubhouse', 'gated', 'greenPickleball'),
    ('Del Webb', 'del-webb', '861eb358-8673-4cac-9c45-5299f9201079', 'https://www.lifeatlakewood.com/del-webb', 'Del Webb', 'scenicWalks', 'gated', 'greenPickleball'),
    ('Edgewater', 'edgewater', 'b88749df-4c7f-4632-8eef-f92564e86e16', 'https://www.lifeatlakewood.com/edgewater', 'Edgewater', 'scenicWalks', 'gated', NULL),
    ('Esplanade Golf & Country Club', 'esplanade-golf-and-country-club', 'd333f9b6-61dd-4f9e-a4c9-31eda20d4e2b', 'https://www.lifeatlakewood.com/esplanade-golf-and-country-club', 'Original Esplanade', 'villageSpa', 'tennis', 'greenGolf2'),
    ('Greenbrook Village', 'greenbrook-village', '848b5723-347c-4457-95d9-f5dc989363a6', 'https://www.lifeatlakewood.com/greenbrook-village', 'Greenbrook Village', 'villageSpa', 'tennis', 'dogPark'),
    ('Harmony', 'harmony', '0a7da735-4136-4a98-9d4b-2631293bba0e', 'https://www.lifeatlakewood.com/harmony', 'Harmony', 'clubhouse', 'totLot', 'villagePool'),
    ('Indigo', 'indigo', '224cc2b4-5375-4acd-bfdc-2956be570350', 'https://www.lifeatlakewood.com/indigo', 'Indigo', 'clubhouse', 'totLot', 'greenPickleball'),
    ('Lakewood National', 'lakewood-national', 'f79f9fce-77b8-4f1b-b145-3b4bddaa016c', 'https://www.lifeatlakewood.com/lakewood-national', 'Lakewood National', 'clubhouse', 'gated', 'greenGolf2'),
    ('Lorraine Lakes', 'lorraine-lakes', '86da6c3e-3055-4b22-9ce5-c312bb63a046', 'https://www.lifeatlakewood.com/lorraine-lakes', 'Lorraine Lakes', 'scenicWalks', 'totLot', 'greenTennis'),
    ('Mallory Park', 'mallory-park', '2f752a9d-68e2-47df-8bb2-d43897def90a', 'https://www.lifeatlakewood.com/mallory-park', 'Mallory Park', 'clubhouse', 'gated', 'greenPickleball'),
    ('Palisades', 'palisades', '1ce48cc7-fd95-4621-8532-4f371752ed54', 'https://www.lifeatlakewood.com/palisades', 'Palisades', 'clubhouse', 'gated', 'villagePool'),
    ('Polo Run', 'polo-run', 'cb44f492-711e-46ac-9b14-94a884cd2148', 'https://www.lifeatlakewood.com/polo-run', 'Polo Run', 'clubhouse', 'gated', 'greenTennis'),
    ('Sapphire Point', 'sapphire-point', 'df7652e1-8e7b-4804-bf8c-70b0e1262868', 'https://www.lifeatlakewood.com/sapphire-point', 'Sapphire Point', 'clubhouse', 'gated', 'dogPark'),
    ('Savanna', 'savanna', 'fd4f3104-77c3-4f02-953e-fde4dba58ec4', 'https://www.lifeatlakewood.com/savanna', 'Savanna', 'clubhouse', 'gated', 'dogPark'),
    ('Solera', 'solera', '849b17da-ccf0-407c-a850-42b2650e6eb7', 'https://www.lifeatlakewood.com/solera', 'Solera', 'clubhouse', 'totLot', 'villagePool'),
    ('Star Farms', 'star-farms', 'd0285478-446b-408f-8e64-67720f4599d7', 'https://www.lifeatlakewood.com/star-farms', 'Star Farms', 'clubhouse', 'tennis', 'greenPickleball'),
    ('Summerfield', 'summerfield-and-riverwalk', '5a88ccbb-3ebf-4545-87bb-4e1599415b0e', 'https://www.lifeatlakewood.com/summerfield-and-riverwalk', 'Summerfield', 'scenicWalks', 'totLot', 'greenTennis'),
    ('Sweetwater', 'sweetwater', 'b963c227-7acb-47e1-a81b-31c29cfe7007', 'https://www.lifeatlakewood.com/sweetwater', 'Sweetwater', 'clubhouse', 'totLot', 'greenPickleball'),
    ('The Country Club', 'country-club', '39b23fe1-5893-4b62-a2aa-cf87e0df6694', 'https://www.lifeatlakewood.com/country-club', 'The Country Club', 'villageSpa', 'gated', 'greenGolf2'),
    ('The Isles', 'the-isles', 'b44fc9cf-68cb-4abd-aec9-bcae4f829875', 'https://www.lifeatlakewood.com/the-isles', 'The Isles', 'clubhouse', 'gated', 'greenTennis'),
    ('The Lake Club', 'the-lake-club', '9dfd1bad-e515-4cdb-b73b-d4f122b00bcc', 'https://www.lifeatlakewood.com/the-lake-club', 'The Lake Club', 'villageSpa', 'gated', 'greenPickleball'),
    ('Waterside - Avanti', 'waterside-avanti', '546e31bc-56ff-451f-93fa-6c9487261d68', 'https://www.lifeatlakewood.com/waterside-avanti', 'Avanti - Waterside', 'maintenance', NULL, NULL),
    ('Waterside - Emerald Landing', 'waterside-emerald-landing', '5ee249ae-9ee9-4481-b1e1-430fb96b8f7c', 'https://www.lifeatlakewood.com/waterside-emerald-landing', 'Emerald Landing - Waterside', 'clubhouse', 'tennis', 'dogPark'),
    ('Waterside - LakeHouse Cove', 'waterside-lakehouse-cove', '65a10f06-4ee7-4f40-a7fd-35dd80a9fded', 'https://www.lifeatlakewood.com/waterside-lakehouse-cove', 'LakeHouse Cove - Waterside', 'clubhouse', 'tennis', 'greenPickleball'),
    ('Waterside - Nautique', 'waterside-nautique', 'b6cc0bcb-5bfd-47ca-930a-b64420a09493', 'https://www.lifeatlakewood.com/waterside-nautique', 'Nautique - Waterside', 'scenicWalks', 'totLot', 'greenPickleball'),
    ('Waterside - Shellstone', 'waterside-shellstone', '1b62edcc-23fc-45c2-9f7b-63bf9fcc4efd', 'https://www.lifeatlakewood.com/waterside-shellstone', 'Shellstone - Waterside', 'clubhouse', 'tennis', 'greenPickleball'),
    ('Waterside - Shoreview', 'waterside-shoreview', '123379b1-1f66-4f08-af66-3c71917db022', 'https://www.lifeatlakewood.com/waterside-shoreview', 'Shoreview - Waterside', 'clubhouse', 'tennis', 'greenPickleball'),
    ('Waterside - The Alcove', 'waterside-the-alcove', '2e8a6259-2bbd-4000-ac8d-f019d8329d3f', 'https://www.lifeatlakewood.com/waterside-the-alcove', 'The Alcove - Waterside', 'scenicWalks', NULL, NULL),
    ('Waterside - Wild Blue', 'waterside-wild-blue', 'd66b8553-79bf-4d53-8d48-7e8d145a1d0f', 'https://www.lifeatlakewood.com/waterside-wild-blue', 'Wild Blue - Waterside', 'clubhouse', 'tennis', 'greenPickleball'),
    ('Windward', 'windward', '607ac859-6946-459e-868b-b32f590ec4d0', 'https://www.lifeatlakewood.com/windward', 'Windward', 'kidsTotlot', 'tennis', 'greenPickleball'),
    ('Woodleaf Hammock', 'woodleaf-hammock', '8dbceaba-b54a-4b58-b85a-4690d3b1c28b', 'https://www.lifeatlakewood.com/woodleaf-hammock', 'Woodleaf Hammock', 'scenicWalks', 'totLot', 'dogPark')
)
INSERT INTO ls_villages (site_id, name, wix_slug, wix_item_id, page_url, display)
SELECT site.id, v.name, v.wix_slug, v.wix_item_id, v.page_url,
       jsonb_strip_nulls(jsonb_build_object('villageSortHelp', v.sort_help, 'blueTag1', b.url, 'purpleTag1', p.url, 'greenTag1', g.url))
  FROM village_rows v
  CROSS JOIN site
  LEFT JOIN icon b ON b.key = v.blue
  LEFT JOIN icon p ON p.key = v.purple
  LEFT JOIN icon g ON g.key = v.green
ON CONFLICT (site_id, name) DO UPDATE SET wix_slug = EXCLUDED.wix_slug, wix_item_id = EXCLUDED.wix_item_id, page_url = EXCLUDED.page_url, display = EXCLUDED.display, updated_at = now();

WITH site AS (SELECT id FROM ls_sites WHERE domain = 'lifeatlakewood.com'),
term_rows(village_name, term, exclude_term) AS (VALUES
    ('Arbor Grande', 'arbor grande', NULL),
    ('Aurora', 'aurora', NULL),
    ('Avalon Woods', 'avalon woods', NULL),
    ('Azario - Esplanade', 'azario esplanade', NULL),
    ('Azario - Esplanade', 'esplanade at azario', NULL),
    ('Azario - Esplanade', 'azario lakewood ranch', NULL),
    ('Azario - Park East', 'park east at azario', NULL),
    ('Bridgewater', 'bridgewater ph', NULL),
    ('Central Park', 'central park subphase', NULL),
    ('Central Park', 'central park lakewood', NULL),
    ('Central Park', 'central park  lakewood', NULL),
    ('Country Club East', 'country club east', NULL),
    ('Cresswind', 'cresswind', NULL),
    ('Del Webb', 'del webb', NULL),
    ('Edgewater', 'edgewater village', NULL),
    ('Edgewater', 'moorings at edgewater', NULL),
    ('Esplanade Golf & Country Club', 'esplanade ph', 'azario'),
    ('Esplanade Golf & Country Club', 'esplanade phase', 'azario'),
    ('Esplanade Golf & Country Club', 'esplanade golf', 'azario'),
    ('Esplanade Golf & Country Club', 'esplanade at lakewood', 'azario'),
    ('Esplanade Golf & Country Club', 'esplanade lakewood', 'azario'),
    ('Esplanade Golf & Country Club', 'bacciano', NULL),
    ('Greenbrook Village', 'greenbrook', NULL),
    ('Harmony', 'harmony at lakewood', NULL),
    ('Indigo', 'indigo', NULL),
    ('Lakewood National', 'lakewood national', NULL),
    ('Lakewood National', 'lakewood natl', NULL),
    ('Lakewood National', 'lakewood ntl', NULL),
    ('Lorraine Lakes', 'lorraine lakes', NULL),
    ('Mallory Park', 'mallory park', NULL),
    ('Palisades', 'palisades', NULL),
    ('Polo Run', 'polo run', NULL),
    ('Sapphire Point', 'sapphire point', NULL),
    ('Savanna', 'savanna at lakewood', NULL),
    ('Solera', 'solera at lakewood', NULL),
    ('Solera', 'lakewood ranch solera', NULL),
    ('Star Farms', 'star farms', NULL),
    ('Summerfield', 'summerfield hollow', NULL),
    ('Summerfield', 'summerfield village', NULL),
    ('Summerfield', 'riverwalk ridge', NULL),
    ('Summerfield', 'riverwalk village', NULL),
    ('Sweetwater', 'sweetwater at lakewood', NULL),
    ('Sweetwater', 'sweetwater villas at lakewood', NULL),
    ('The Country Club', 'lakewood ranch country club', NULL),
    ('The Country Club', 'lakewood ranch cc', NULL),
    ('The Isles', 'isles at lakewood ranch', NULL),
    ('The Lake Club', 'lake club', NULL),
    ('Waterside - Avanti', 'avanti at waterside', NULL),
    ('Waterside - Avanti', 'avanti/waterside', NULL),
    ('Waterside - Emerald Landing', 'emerald lndg', NULL),
    ('Waterside - Emerald Landing', 'emerald landing', NULL),
    ('Waterside - LakeHouse Cove', 'lakehouse cove', NULL),
    ('Waterside - Nautique', 'nautique', NULL),
    ('Waterside - Shellstone', 'shellstone', NULL),
    ('Waterside - Shoreview', 'shoreview', NULL),
    ('Waterside - The Alcove', 'alcove at waterside', NULL),
    ('Waterside - The Alcove', 'alcove/waterside', NULL),
    ('Waterside - Wild Blue', 'wild blue', NULL),
    ('Windward', 'windward at lakewood', NULL),
    ('Windward', 'windward/lakewood', NULL),
    ('Woodleaf Hammock', 'woodleaf hammock', NULL)
)
INSERT INTO ls_village_terms (site_id, village_id, term, exclude_term)
SELECT site.id, v.id, t.term, t.exclude_term FROM term_rows t JOIN site ON true JOIN ls_villages v ON v.site_id = site.id AND v.name = t.village_name
ON CONFLICT DO NOTHING;
